on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image and ping
      run: |
        docker build -t dguest390/shiny-dashboard .
        docker run -dp 3838:3838 dguest390/shiny-dashboard
        sleep 10s
        curl http://127.0.0.2:3838
